version: "3.9"

services:
  backend:
    build: ../backend
    container_name: omd-backend
    ports:
      - "8080:8080"
    networks:
      - omd-network

  frontend:
    build: ../frontend
    container_name: omd-frontend
    ports:
      - "3000:80"
    networks:
      - omd-network

  nginx:
    image: nginx:latest
    container_name: omd-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - omd-network

networks:
  omd-network:
    driver: bridge
