version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: omd-frontend
    restart: always
    networks:
      - omd-network

  backend:
    build:
      context: ./backend
    container_name: omd-backend
    restart: always
    ports:
      - "8080:8080" # opcional, pode remover se só acessar via proxy
    networks:
      - omd-network

  nginx:
    image: nginx:latest
    container_name: omd-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/www:/var/www/certbot # opcional se quiser SSL
    depends_on:
      - frontend
      - backend
    networks:
      - omd-network

networks:
  omd-network:
    driver: bridge
